### ISSUE TITLE
Show hand icon as mouse pointer

### ISSUE THREAD

**Issue by joergreichert** [The-Villains/MajorelleMysteryApp#8]
as long as we have no player figure yet, we will use the mouse pointer as interaction symbole

**Comment by soheinze** [comment]
Simple implementation is possible via project settings -> Display -> Mouse Cursor

Current image of the hand is too big though, didn't see how to resize it from within the game and we might need to figure out how to properly adjust the Image Hotspot and Tooltip Position Offset.

**Comment by joergreichert** [comment]
Maybe we leave the mouse pointer as it is, as we now have the character in place.
